### ISSUE TITLE
PermissionError: [Errno 13] Permission denied ...geckodriver.exe

### ISSUE THREAD

**Issue by FarisHijazi** [HamedMinaeizaeim/twitter_scraper#2]
code ran:

```py
from twitter_scraper_without_api import TwitterScraper
twitter = TwitterScraper('bitcoin')
```

output error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\site-packages\twitter_scraper_without_api\twitter_scraper.py", line 35, in __init__
    self.driver = self.setup_driver()
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\site-packages\twitter_scraper_without_api\twitter_scraper.py", line 92, in setup_driver
    driver = firefox.set_driver_for_browser()
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\site-packages\twitter_scraper_without_api\driver_initialisation.py", line 68, in set_driver_for_browser
    return webdriver.Firefox(executable_path=GeckoFireFoxdriverManager().install_geckodriver(),
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\site-packages\py_firefox_driver_manager\Utilities.py", line 137, in install_geckodriver
    self.uncompress(zipfilename, self.directory)
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\site-packages\py_firefox_driver_manager\Utilities.py", line 66, in uncompress
    zip_ref.extractall(directory)
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\fhijazi\Anaconda3\envs\labeling\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\fhijazi\\OneDrive\\Projects\\firefox-geckodriver\\geckodriver.exe'
```

**Comment by FarisHijazi** [comment]
nevermind, it was an issue from `from py_firefox_driver_manager import GeckoFireFoxdriverManager` and it had the file open twice somehow, maybe because OneDrive

restarting the python session fixed it
